name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-minify-plugin
          pip install mkdocs-material   # if you're using Material theme
          # pip install mkdocs-awesome-pages-plugin  # add more if needed

      - name: Build and Deploy
        run: mkdocs gh-deploy --force --remote-name origin
